[package]
name = "uno-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitflags = { version = "2.6.0", features = ["std"] }
bytes = "1.7.1"
num_enum = "0.7.3"
tokio = { version = "1.39.2", features = ["full"] }
